const roomdetails=[{
    id:1,
    seats : 100,
    hour_price : 100,
    AC: "Available",
    status:"Available",
    CustomerName:"",
    Date:"",
    StartTime:"",
    EndTime:"",
},
{
    id:2,
    seats : 100,
    hour_price : 100,
    AC: "Available",
    status:"Available",
    CustomerName:"",
    Date:"",
    StartTime:"",
    EndTime:"",
},
{
    id:3,
    seats : 100,
    hour_price : 70,
    AC: "Not Available",
    status:"Available",
    CustomerName:"",
    Date:"",
    StartTime:"",
    EndTime:"",
},
{
    id:4,
    seats : 100,
    hour_price : 100,
    AC: "Available",
    status:"Available",
    CustomerName:"",
    Date:"",
    StartTime:"",
    EndTime:"",
},
{
    id:5,
    seats : 100,
    hour_price : 70,
    AC: "NotAvailable",
    status:"Available",
    CustomerName:"",
    Date:"",
    StartTime:"",
    EndTime:"",
}]
module.exports=roomdetails;